abs_urls: false
admin_theme: true
roles_profiles:
  authenticated:
    public: member
    private: member
  administrator:
    public: admin
    private: admin
_core:
  default_config_hash: 4FhrEwOM9yJ8neEoN77sxroTRBUXqRwap0KSJtFnYJs
