features:
  node_user_picture: 0
  comment_user_picture: true
  comment_user_verification: true
  favicon: 1
logo:
  use_default: 0
  path: ''
favicon:
  use_default: 0
  path: 'public://index.ico'
  mimetype: image/vnd.microsoft.icon
